# -*- coding: utf-8 -*-
"""220041122_Lab3_1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDIzb5gKVLje_-579RS04ZM9tQfuyL3E
"""

# Commented out IPython magic to ensure Python compatibility.
#loading libraries
import pandas as pd
import numpy as np
import matplotlib . pyplot as plt
import seaborn as sns

from sklearn . model_selection import train_test_split
from sklearn . preprocessing import StandardScaler ,OrdinalEncoder

# sklearn models -- used in the Bonus section only
from sklearn . linear_model import LinearRegression ,Lasso , Ridge
from sklearn . metrics import mean_squared_error ,r2_score

# %matplotlib inline
sns . set_theme ( style ="whitegrid")
print ("All libraries loaded successfully !")

df = pd . read_csv ("diamonds.csv")

print( f" Shape : {df. shape }")
df.head()

df.info()

print ( df . describe () )

# Physical dimensions should never be zero for a real diamond
bad = df [( df ['x'] == 0) | ( df ['y'] == 0) | ( df ['z'] ==0) ]
print ( f"\ nRows with x=0 , y=0 , or z=0 ( invalid ): {len(bad )}")

plt . figure ( figsize =(11 , 4) )

plt . subplot (1 , 2 , 1)
plt . hist ( df ['price'] , bins =50 , color ='steelblue', edgecolor ='white')

plt . title (" Distribution of Price (Raw)")
plt . xlabel (" Price (USD)")
plt . ylabel (" Count ")

plt . subplot (1 , 2 , 2)
plt . hist ( np . log1p ( df ['price']) , bins =50 , color ='darkorange', edgecolor ='white')
plt . title (" Distribution of log (1 + Price )")
plt . xlabel ("log (1 + Price )")
plt . ylabel (" Count ")

plt . suptitle (" Diamond Price : Raw vs. Log - Transformed ", fontsize =13)
plt . tight_layout ()
plt . show ()

print ( f" Price range : ${df[ 'price']. min ()} -- ${df[ 'price']. max ()}")
print ( f" Mean price : ${df[ 'price']. mean () :.0f}")
print ( f" Median price : ${df[ 'price']. median () :.0f}")

num_features = ['carat', 'depth', 'table', 'x', 'y', 'z']

fig , axes = plt . subplots (2 , 3 , figsize =(14 , 8) )
axes = axes . flatten ()

for i , col in enumerate ( num_features ) :
  axes [ i ]. scatter ( df [ col ] , df ['price'] , alpha =0.08 , color ='steelblue', s =5)
  axes [ i ]. set_xlabel ( col )
  axes [ i ]. set_ylabel (" Price (USD)")
  axes [ i ]. set_title ( f"{col} vs Price ")

plt . suptitle (" Numerical Features vs. Diamond Price ", fontsize =13 , y =1.01)
plt . tight_layout ()
plt . show ()

"""Task 1 : Data Loading and Preprocessing"""

#dropping invalid rows
df_clean = df [( df ['x'] > 0) & ( df ['y'] > 0) & ( df ['z']> 0) ]. copy ()
print ( f" Rows before : {len(df)}")
print ( f" Rows after : {len( df_clean )}")

#choosing random sample rows of 5000,
df_sample = df_clean . sample ( n =5000 , random_state =42).reset_index ( drop = True )
print ( f" Sample shape : { df_sample . shape }")
print ( f" Price range in sample : ${ df_sample ['price'].min ()} "f" -- ${ df_sample ['price']. max ()}")

#encoding
cut_order = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
color_order = ['J', 'I', 'H', 'G', 'F', 'E', 'D']
clarity_order = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']

enc = OrdinalEncoder ( categories =[ cut_order , color_order , clarity_order ])

df_sample [[ 'cut', 'color', 'clarity']] = enc.fit_transform (df_sample [[ 'cut', 'color', 'clarity']])

print ( df_sample [[ 'cut', 'color', 'clarity']]. head () )

feature_cols = ['carat', 'cut', 'color', 'clarity','depth', 'table', 'x', 'y', 'z']
target_col = 'price'

X_raw = df_sample [ feature_cols ]. values . astype ( float )
y = df_sample [ target_col ]. values . astype ( float )

print (" Feature matrix shape :", X_raw . shape ) # (5000 ,9)
print (" Target vector shape :", y . shape ) #(5000 ,)

#splitting test and train data
X_train , X_test , y_train , y_test = train_test_split (
X_raw , y , test_size =0.2 , random_state =42)

print ( f" Training samples : { X_train . shape [0]} ")
print ( f" Test samples : { X_test . shape [0]} ")
print ( f" Number of features : { X_train . shape [1]} ")

scaler = StandardScaler ()
X_train_scaled = scaler . fit_transform ( X_train ) # fit + transform on train
X_test_scaled = scaler . transform ( X_test ) #transform only on test

print (" Training feature means ( should be ~0):")
print ( X_train_scaled . mean ( axis =0) . round (4) )
print ("\nTraining feature stds ( should be ~1):")
print ( X_train_scaled . std ( axis =0) . round (4) )

def add_bias ( X ) :
  """ Prepend a column of ones to matrix X."""
  ones = np . ones (( X . shape [0] , 1) )
  return np . hstack ([ ones , X ])

X_train_b = add_bias ( X_train_scaled )
X_test_b = add_bias ( X_test_scaled )

print ("Shape after adding bias column :")
# (4000 , 10) -- 9 features + 1 bias column

print("X_train_b shape:", X_train_b.shape)   # (4000, 10)
print("X_test_b shape: ", X_test_b.shape)    # (1000, 10)

"""Task 2: Hypothesis and Loss"""

#predicts value for only 1 sample
def predict_single(x, w):
    y_hat = 0

    for i in range(len(w)):
        y_hat += w[i] * x[i]

    return y_hat

#for whole dataset
def predict(X, w):
    predictions = []

    for i in range(len(X)):
        pred = predict_single(X[i], w)
        predictions.append(pred)

    return np.array(predictions)

def mse_loss(X, y, w):
    y_pred = predict(X, w)
    mse = np.mean((y - y_pred) ** 2)
    return mse

w = np.zeros(X_train_b.shape[1])

y_pred = predict(X_train_b, w) #predictions before training

print("First 5 predictions vs true values:")
for i in range(5):
    print(f"Predicted: {y_pred[i]:.2f}, True: {y_train[i]:.2f}")

"""All 5 predictions are 0.00 because all weights are zero. The model predicts
the same value (zero) regardless of the input. This confirms the model has
learned nothing yet — training is needed to find useful weights.
"""

loss = mse_loss(X_train_b, y_train, w)
print("\nInitial Training MSE Loss:", loss)

"""Task 3: Gradient Descent"""

#weights taken randomly
w = np.random.uniform(-1, 1, X_train_b.shape[1])

print(w)

def compute_gradients(X, y, w):
    gradients = np.zeros_like(w)
    y_pred = predict(X, w)

    n  = len(X)
    for i in range(n):
      error = y_pred[i] - y[i] #errors calc for each prediction
      for j in range(len(w)):
          gradients[j] += 2 * (error * X[i][j]) / n #gradients formula

    return gradients

def gradient_descent_step(w, grads, lr):
  for j in range(len(w)):
        w[j] = w[j] - lr * grads[j] #weight adjustment

  return w

train_mse = []
test_mse = []

#training
for epoch in range(300):

    grads = compute_gradients(X_train_b, y_train, w)

    w = gradient_descent_step(w, grads, 0.05) #updated using gradients and learning rate

    train_mse.append(mse_loss(X_train_b, y_train, w))
    test_mse.append(mse_loss(X_test_b, y_test, w))

    if epoch % 50 == 0:
        print(f"Epoch {epoch}: MSE = {test_mse[-1]:.2f}")

plt.figure(figsize=(10, 5))

plt.plot(train_mse, label='Training MSE')
plt.plot(test_mse, label='Test MSE')
plt.xlabel('Epochs')
plt.ylabel('MSE')
plt.legend()
plt.show()

"""Task 4: Gradient Descent — With Regularization"""

def mse_loss_l2(X, y, w, lamda):
    y_pred = predict(X, w)
    val1   = np.mean((y - y_pred) ** 2)
    val2   = lamda * np.sum(w[1:] ** 2)   # skip bias (index 0)
    return val1 + val2

def mse_loss_l1(X, y, w, lamda):
    y_pred = predict(X, w)
    val1   = np.mean((y - y_pred) ** 2)
    val2   = lamda * np.sum(np.abs(w[1:]))  # skip bias (index 0)
    return val1 + val2

def compute_gradients_l2(X, y, w, lamda):
    gradients = np.zeros_like(w)
    y_pred    = predict(X, w)
    n         = len(X)

    for i in range(n):
        error = y_pred[i] - y[i]
        for j in range(len(w)):
            gradients[j] += (2 * error * X[i][j]) / n

    for j in range(1, len(w)):
        gradients[j] += 2 * lamda * w[j] / n

    return gradients

def sign(x):
    if x > 0:
        return 1
    elif x < 0:
        return -1
    else:
        return 0

def compute_gradients_l1(X, y, w, lamda):
  gradients = np.zeros_like(w)
  y_pred    = predict(X, w)
  n         = len(X)

  for i in range(n):
    error = y_pred[i] - y[i]
    for j in range(len(w)):
      gradients[j] += (2 * error * X[i][j]) / n

  for j in range(1, len(w)):
    gradients[j] += lamda * sign(w[j])/ n

  return gradients

lamda = 100
lr = 0.05
epochs = 300

w_ridge = np.random.uniform(-1, 1, X_train_b.shape[1])

ridge_train_mse = []
ridge_test_mse = []

for epoch in range(epochs):
    grads   = compute_gradients_l2(X_train_b, y_train, w_ridge, lamda)
    w_ridge = gradient_descent_step(w_ridge, grads, lr)

    ridge_train_mse.append(mse_loss_l2(X_train_b, y_train, w_ridge, lamda))
    ridge_test_mse.append(mse_loss(X_test_b, y_test, w_ridge))

    if epoch % 50 == 0:
        print(f"Epoch {epoch}: Ridge Test MSE = {ridge_test_mse[-1]:.2f}")

w_lasso = np.random.uniform(-1, 1, X_train_b.shape[1])

lasso_train_mse = []
lasso_test_mse = []

for epoch in range(epochs):
    grads   = compute_gradients_l1(X_train_b, y_train, w_lasso, lamda)
    w_lasso = gradient_descent_step(w_lasso, grads, lr)

    lasso_train_mse.append(mse_loss_l1(X_train_b, y_train, w_lasso, lamda))
    lasso_test_mse.append(mse_loss(X_test_b, y_test, w_lasso))

    if epoch % 50 == 0:
        print(f"Epoch {epoch}: Lasso Test MSE = {lasso_test_mse[-1]:.2f}")

"""Regularization slightly increases test MSE here compared to plain linear
regression. This is expected when the model is not heavily overfitting —
the penalty trades some fit quality for weight stability. Ridge and Lasso
are most beneficial when features are highly correlated or when the model
has many more features than samples.

Task 5: Comparison and Analysis
"""

plt.figure(figsize=(10, 5))

plt.plot(test_mse,label='Linear Regression')
plt.plot(ridge_test_mse,label='Ridge')
plt.plot(lasso_test_mse,label='Lasso')
plt.xlabel("Epochs")
plt.ylabel("Test MSE")
plt.title("Test MSE Comparison: Linear vs Ridge vs Lasso")

plt.legend()
plt.show()

lambdas = [1, 10, 100, 500, 1000, 5000]
final_test_mse = []

for lamda in lambdas:
    w_temp = np.random.uniform(-1, 1, X_train_b.shape[1])

    for epoch in range(300):
        grads  = compute_gradients_l2(X_train_b, y_train, w_temp, lamda)
        w_temp = gradient_descent_step(w_temp, grads, 0.05)

    mse = mse_loss(X_test_b, y_test, w_temp)
    final_test_mse.append(mse)
    print(f"Lambda = {lamda}, Test MSE = {mse:.2f}")

plt.figure(figsize=(8, 5))

plt.plot(lambdas, final_test_mse, marker='o')
plt.xscale('log')
plt.xlabel("Lambda")
plt.ylabel("Final Test MSE")
plt.title("Ridge: Test MSE vs Lambda")

plt.grid(True)
plt.show()

best_index  = np.argmin(final_test_mse)
best_lambda = lambdas[best_index]
print("Best lambda:", best_lambda)
print("Lowest Test MSE:", final_test_mse[best_index])

"""As lambda increases the feature weights shrink toward zero because the penalty grows proportionally to weight magnitude.  Very small lambda
(~1) barely differs from plain linear regression.  There is a sweet spot
(the best_lambda found above) that balances bias and variance.  A very
large lambda (e.g. 5000) drives nearly all weights to zero, causing severe
underfitting and a high test MSE — the model essentially predicts the mean.

Task 6 : Scikit-Learn Comparison
"""

X_train_m = X_train_scaled.copy()
X_test_m  = X_test_scaled.copy()

lr_model = LinearRegression()
lr_model.fit(X_train_m, y_train)
lr_pred = lr_model.predict(X_test_m)
lr_mse  = mean_squared_error(y_test, lr_pred)

ridge_model = Ridge(alpha=100)
ridge_model.fit(X_train_m, y_train)
ridge_pred = ridge_model.predict(X_test_m)
ridge_mse  = mean_squared_error(y_test, ridge_pred)

lasso_model = Lasso(alpha=100)
lasso_model.fit(X_train_m, y_train)
lasso_pred = lasso_model.predict(X_test_m)
lasso_mse  = mean_squared_error(y_test, lasso_pred)

print("Sklearn models trained.")

manual_linear_mse = test_mse[-1]
manual_ridge_mse  = ridge_test_mse[-1]
manual_lasso_mse  = lasso_test_mse[-1]

comparison = pd.DataFrame({
    "Model":              ["Linear Regression", "Ridge", "Lasso"],
    "Our Implementation": [manual_linear_mse, manual_ridge_mse, manual_lasso_mse],
    "Sklearn":            [lr_mse, ridge_mse, lasso_mse]
})
print(comparison)

weight_compare = pd.DataFrame({
    "Feature":         feature_cols,       # 9 feature names
    "Our Weights":     w[1:],              # w[1:] — skip bias at index 0
    "Sklearn Weights": lr_model.coef_      # 9 feature weights
})
print(weight_compare)
print(f"\nBias term  — Ours: {w[0]:.4f} | Sklearn intercept: {lr_model.intercept_:.4f}")

"""
The bias terms match exactly (3858.14), confirming our intercept is correct.
Feature weight differences exist for two reasons:
1. Convergence: our training runs 300 epochs and hasn't fully converged. Sklearn solves the normal equations (X^T X)^{-1} X^T y exactly in one step and uses it directly.
2. Multicollinearity: carat, x, y, z are all highly correlated (r > 0.95). In this setting there are many weight combinations that produce nearly identical predictions. Manual version drifts to one solution, sklearn finds another. Both are valid — the similar MSE values confirm this.
To reduce the weight gap, we could do the following:
- Train for more epochs (e.g. 2000+)
- Use learning rate decay
- Apply Ridge regularization, which forces a unique solution even under multicollinearity by penalising large weights"""

# verify predictions are similar despite different weights
our_pred    = predict(X_test_b, w)          # uses w[0] as bias automatically
sklearn_pred = lr_model.predict(X_test_m)   # sklearn handles intercept internally

print(f"Our MSE:     {np.mean((y_test - our_pred)**2):.2f}")
print(f"Sklearn MSE: {np.mean((y_test - sklearn_pred)**2):.2f}")
print(f"\nFirst 5 prediction comparison:")
print(f"{'True':>10} {'Ours':>10} {'Sklearn':>10}")
for i in range(5):
    print(f"{y_test[i]:>10.2f} {our_pred[i]:>10.2f} {sklearn_pred[i]:>10.2f}")