# -*- coding: utf-8 -*-
"""220041122_1B_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yC4FqfjzHJti9OFJ8YUmqFDx6dyTKpYt

Task 1

Importing all libraries and setting up the environment
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
from sklearn . preprocessing import LabelEncoder , OneHotEncoder
from sklearn . preprocessing import MinMaxScaler , StandardScaler

# %matplotlib inline

sns.set_theme(style="whitegrid")

"""Loading CSV file and displaying 10 rows"""

file_path = "/content/titanic.csv"
df = pd.read_csv(file_path)

df.head(10)

"""Shape, column names, data types info"""

print("Shape:", df.shape)

print("\nDataset Info:")
df.info()

"""Numerical vs categorical"""

print("\nCategorical Summary:")
df.describe(include='object')

print("\nNumerical Summary:")
df.describe()

"""Finding people who paid more than average"""

# first we find any missing values
print("Missing Values:")
print(df.isnull().sum())

fare_mean = df['Fare'].mean()

more = df[df['Fare'] > fare_mean]

print("People who paid more than average fare:")
print(more['Name'].head(100))

"""Percentage of missing vals for all column sorted in descending order"""

percent_missing = df.isnull().mean()*100

percent_missing.sort_values(ascending=False)

"""Task 2"""

df = df.drop(columns=['Cabin'])

plt.hist(df['Age'], bins=30, edgecolor='white')
plt.title("Age Distribution Before Imputation")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

age_median = df ['Age'].median()
print (f" Median age: { age_median }")
df ['Age'] = df ['Age']. fillna ( age_median )

# verify no more missing values in Age
print ( f" Missing in Age after imputation : {df['Age'].isnull ().sum ()}")

plt.hist(df['Age'], bins=30, edgecolor='white')
plt.title("Age Distribution After Imputation")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

embarked_mode = df['Embarked'].mode()[0]

df['Embarked'] = df['Embarked']. fillna( embarked_mode )
print ( f" Missing in Embarked after imputation : {df['Embarked']. isnull ().sum ()}")

# final missing check
df.isnull().sum()

le = LabelEncoder ()
df['Sex_encoded'] = le.fit_transform(df['Sex'])

# check the mapping
print (" Classes :", le.classes_) # [ ’ female ’, ’male ’]
print (df[[ 'Sex', 'Sex_encoded']].head())

#sex is encoded

# pd. get_dummies is the easiest way to one -hot encode
embarked_dummies = pd.get_dummies(df['Embarked'] ,prefix ='Embarked', drop_first = True)

df = pd.concat([df, embarked_dummies], axis=1)
df = df.drop(columns=['Sex', 'Embarked'])

df.head()

#one hot encoding done

minmax = MinMaxScaler ()
# fit on training data and transform
df [[ 'Age_minmax', 'Fare_minmax']] = minmax.fit_transform ( df [[ 'Age', 'Fare']])
print ( df [[ 'Age', 'Age_minmax', 'Fare', 'Fare_minmax']]. head() )

print("Age_minmax range:", df['Age_minmax'].min(), df['Age_minmax'].max())
print("Fare_minmax range:", df['Fare_minmax'].min(), df['Fare_minmax'].max())

"""Standardization"""

std = StandardScaler()
df[['Age_std', 'Fare_std']] = std.fit_transform(df[['Age', 'Fare']])

df[['Age', 'Age_std', 'Fare', 'Fare_std']].head()

"""Task 4

Histogram of fare distribution
"""

plt.hist(df['Fare'], bins=30, edgecolor='white')
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

"""Bar chart of number of passengers who survived and didnt"""

df['Survived'].value_counts().plot(kind='bar')
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

"""Box plots of Fare for each passenger class"""

sns.boxplot(data=df, x='Pclass', y='Fare')
plt.title("Fare by Passenger Class")
plt.xlabel("Pclass")
plt.ylabel("Fare")
plt.show()

"""Pearson correlation matrix"""

numeric_df = df.select_dtypes(include=[np.number])

corr = numeric_df.corr()

plt.figure(figsize=(10,7))
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""KDE of Age for male and female passengers"""

# original dataset for Sex column
df_original = pd.read_csv(file_path)

df_original['Age'] = df_original['Age'].fillna(df_original['Age'].median())

sns.kdeplot(data=df_original, x='Age', hue='Sex', fill=True)
plt.title("Age Distribution by Gender")
plt.xlabel("Age")
plt.ylabel("Density")
plt.show()

"""Task 5"""

plt.figure(figsize=(6,4))

sns.barplot(data=df, x='Sex_encoded', y='Survived')

plt.title("Survival Rate by Gender")
plt.xlabel("Sex (0 = Female, 1 = Male)")
plt.ylabel("Survival Rate")
plt.show()

df['Age_group'] = df['Age'].apply(lambda x: 'Child' if x < 16 else 'Adult')

plt.figure(figsize=(6,4))

sns.barplot(data=df, x='Age_group', y='Survived')

plt.title("Survival Rate: Children vs Adults")
plt.xlabel("Age Group")
plt.ylabel("Survival Rate")
plt.show()

# combined category
def categorize(row):
    if row['Age'] < 16 and row['Sex_encoded'] == 0:
        return 'Female Child'
    elif row['Age'] < 16 and row['Sex_encoded'] == 1:
        return 'Male Child'
    elif row['Age'] >= 16 and row['Sex_encoded'] == 0:
        return 'Female Adult'
    else:
        return 'Male Adult'

df['Group'] = df.apply(categorize, axis=1)

plt.figure(figsize=(8,5))

sns.countplot(data=df, x='Group', hue='Survived',
              order=['Female Child','Female Adult','Male Child','Male Adult'])

plt.title("Survival Count by Gender and Age Group")
plt.xlabel("Group")
plt.ylabel("Count")
plt.xticks(rotation=20)
plt.legend(title="Survived")
plt.show()