# -*- coding: utf-8 -*-
"""ML_Lab_4_220041122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8MZJy0BEAR3xrLRaGjENG_N9jCdiAci

# Importing Libraries
"""

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report

"""# Reading the Dataset"""

file_path = "/content/heart.csv"  # Change the path if it is different
df = pd.read_csv(file_path)

df.head()

"""# Data Analysis

## Checking the Dataset
"""

print(f"The data types for each column:\n{df.dtypes}")
print(f"\nThe shape of the dataset is: {df.shape}")
print(f"\nThe number of missing values in each column:\n{df.isnull().sum()}")

"""## Distribution of the Target Labels"""

# Count plot of HeartDisease values
sns.countplot(x='HeartDisease', data=df)

plt.title('HeartDisease Value Counts')
plt.xlabel('HeartDisease')
plt.ylabel('Count')
plt.show()

"""# Encoding Categorical Features"""

categorical_cols = ["Sex", "ChestPainType", "RestingECG", "ExerciseAngina", "ST_Slope"]
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print(f"Shape after encoding: {df_encoded.shape}")
print(f"Current columns:\n{df_encoded.columns.tolist()}")

"""# Train-Test Splitting"""

feature_cols = [c for c in df_encoded.columns if c != 'HeartDisease']

X = df_encoded[feature_cols].astype(float)
y = df_encoded['HeartDisease'].astype(float)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set shape: {X_train.shape} | Testing set shape: {X_test.shape}")

"""# Scaling the Columns"""

scaler = StandardScaler()

X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

"""# Tasks Starts Here

## Weight Initialization
"""

def init_weights(num_features, num_hidden_layer, random_seed=42):
    """
    Using Xavier initialization
    """

    random.seed(random_seed)

    W1 = [[random.gauss(0, (2.0 / num_features) ** 0.5) for _ in range(num_features)] for _ in range(num_hidden_layer)]
    b1 = [0.0] * num_hidden_layer

    W2 = [random.gauss(0, (2.0 / num_hidden_layer) ** 0.5) for _ in range(num_hidden_layer)]
    b2 = 0.0

    return W1, b1, W2, b2

"""## Implement the ReLU Function"""

def relu(z):
    # ------------ YOUR CODE STARTS HERE ------------
    return max(0.0, z)
    pass
    # ------------ YOUR CODE ENDS HERE --------------

"""## Implement the Sigmoid Function"""

def sigmoid(z):
    # ------------ YOUR CODE STARTS HERE ------------
    return 1.0 / (1.0 + np.exp(-z))
    pass
    # ------------ YOUR CODE ENDS HERE --------------

"""## Implement the Forward Propagation"""

def forward_prop_single(x, W1, b1, W2, b2):
    """
    Forward pass for a single sample from the dataset
    """

    num_hidden_layer = len(W1)
    num_features = len(x)

    # --- Layer 1: z1 = (W1^T)x + b1 ---
    z1 = []
    for j in range(num_hidden_layer):
        z = 0.0
        for k in range(num_features):
        # ------------ YOUR CODE STARTS HERE ------------
            z += W1[j][k] * x[k]
            pass
        z += b1[j]
        z1.append(z)
        # ------------ YOUR CODE ENDS HERE --------------


    # --- Apply ReLU ---
    a1 = [relu(z) for z in z1]


    # --- Layer 2: z2 = (W2^T)a1 + b2 ---
    z2 = 0.0
    for j in range(num_hidden_layer):
    # ------------ YOUR CODE STARTS HERE ------------
        z2 += W2[j] * a1[j]
        pass

    z2 += b2
    # ------------ YOUR CODE ENDS HERE --------------


    # --- Apply Sigmoid ---
    y_hat = sigmoid(z2)

    return z1, a1, z2, y_hat



def forward_prop(X, W1, b1, W2, b2):
    """
    Returns the predicted probabilities for all the samples in the dataset
    """
    return [forward_prop_single(X[i], W1, b1, W2, b2)[-1] for i in range(len(X))]

"""## Implementing the Binary Cross-Entropy Loss"""

def bce_loss(X, y, W1, b1, W2, b2):
    m = len(y)
    total_loss = 0.0

    for i in range(m):
        _, _, _, y_hat = forward_prop_single(X[i], W1, b1, W2, b2)

        # Numerical clipping to avoid log(0)
        p = max(1e-15, min(1 - 1e-15, y_hat))

        # Calculate BCE loss for sample i and accumulate it in total_loss
        # ------------ YOUR CODE STARTS HERE ------------
        total_loss += -(y[i] * np.log(p) + (1 - y[i]) * np.log(1 - p))
        pass
        # ------------ YOUR CODE ENDS HERE --------------

    return total_loss / m

"""## Implement Backpropagation"""

def backprop(X, y, W1, b1, W2, b2):
    m = len(y)
    num_hidden_layer = len(W1)
    num_features = len(X[0])

    # Initialize gradients
    dW1 = [[0.0] * num_features for _ in range(num_hidden_layer)]
    db1 = [0.0] * num_hidden_layer
    dW2 = [0.0] * num_hidden_layer
    db2 = 0.0

    for i in range(m):
        z1, a1, z2, y_hat = forward_prop_single(X[i], W1, b1, W2, b2)

        # Calculate dW2 and db2
        # ------------ YOUR CODE STARTS HERE ------------
        err = y_hat - y[i]  # dL/dz2

        for j in range(num_hidden_layer):
            dW2[j] += err * a1[j]
        db2 += err
        pass
        # ------------ YOUR CODE ENDS HERE --------------

        # Calculate dW1 and db1
        # ------------ YOUR CODE STARTS HERE ------------
        for j in range(num_hidden_layer):
            if z1[j] > 0:
                err_j = err * W2[j]

                for k in range(num_features):
                    dW1[j][k] += err_j * X[i][k]
                db1[j] += err_j
        pass
        # ------------ YOUR CODE ENDS HERE --------------

    # Average over all samples
    for j in range(num_hidden_layer):
        for k in range(num_features):
            dW1[j][k] /= m
        db1[j] /= m
        dW2[j] /= m
    db2 /= m

    return dW1, db1, dW2, db2

"""## Weight Update"""

def weight_update(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate=0.05):
    num_hidden_layer = len(W1)
    num_features = len(W1[0])

    for j in range(num_hidden_layer):
        for k in range(num_features):
            W1[j][k] -= learning_rate * dW1[j][k]
        b1[j] -= learning_rate * db1[j]
        W2[j] -= learning_rate * dW2[j]
    b2 -= learning_rate * db2

    return W1, b1, W2, b2

"""## Calculate Accuracy"""

def predict_class(X, W1, b1, W2, b2, threshold=0.5):
    return [1 if p >= threshold else 0 for p in forward_prop(X, W1, b1, W2, b2)]

def calculate_accuracy(X, y, W1, b1, W2, b2):
    y_pred = predict_class(X, W1, b1, W2, b2)

    return sum(1 for i in range(len(y)) if y_pred[i] == int(y[i])) / len(y)

"""## Training Loop"""

def train_nn(X_train, y_train, X_test, y_test, num_hidden_layer=16, learning_rate=0.05, epochs=300, random_seed=42):
    """
    Train a two-layer neural network with gradient descent.

    Returns
    -------
    params       : final (W1, b1, W2, b2)
    train_losses, test_losses   : BCE per epoch
    train_accs,   test_accs     : accuracy per epoch
    """
    num_features = len(X_train[0])
    W1, b1, W2, b2 = init_weights(num_features, num_hidden_layer, random_seed=42)

    train_losses, test_losses = [], []
    train_accs, test_accs = [], []

    for epoch in range(epochs):
        # Forward + backward
        dW1, db1, dW2, db2 = backprop(X_train, y_train, W1, b1, W2, b2)
        W1, b1, W2, b2 = weight_update(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate)

        # Record metrics
        tr_loss = bce_loss(X_train, y_train, W1, b1, W2, b2)
        te_loss = bce_loss(X_test,  y_test,  W1, b1, W2, b2)
        tr_acc  = calculate_accuracy(X_train, y_train, W1, b1, W2, b2)
        te_acc  = calculate_accuracy(X_test,  y_test,  W1, b1, W2, b2)

        train_losses.append(tr_loss)
        test_losses.append(te_loss)
        train_accs.append(tr_acc)
        test_accs.append(te_acc)

        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch+1:4d} | "
                  f"Train Loss: {tr_loss:.4f}  Acc: {tr_acc:.4f} | "
                  f"Test Loss: {te_loss:.4f}  Acc: {te_acc:.4f}")

    return (W1, b1, W2, b2), train_losses, test_losses, train_accs, test_accs

"""# Complete the Tasks

## Task 1
"""

params, train_losses, test_losses, train_accs, test_accs = train_nn(X_train_s, y_train, X_test_s, y_test, num_hidden_layer=16, learning_rate=0.05, epochs=300)

"""## Task 2"""

h_sizes = [4, 8, 16, 32]
test_accuracies = []

for H in h_sizes:
    params, train_losses, test_losses, train_accs, test_accs = train_nn(X_train_s, y_train, X_test_s, y_test, num_hidden_layer=H, learning_rate=0.05, epochs=300)

    test_accuracies.append(test_accs[-1])

plt.figure(figsize=(6,4))
plt.plot(h_sizes, test_accuracies, marker='o')
plt.xlabel("Hidden Layer Size (H)")
plt.ylabel("Final Test Accuracy")
plt.title("Final Test Accuracy vs Hidden Layer Size")
plt.grid(True)
plt.show()

print("Results:")
for H, acc in zip(h_sizes, test_accuracies):
    print(f"H = {H:2d} -> Test Accuracy = {acc:.4f}")

"""Role of Hidden Layer Size ($H$):
The hidden layer size $H$ determines the network's capacity to learn geometric boundaries and feature combinations from the input data. If $H$ is too small, the network underfits because it lacks the capacity to map complex, non-linear interactions within the heart dataset features. Conversely, if $H$ is extremely large, the model risks overfitting by memorizing noise in the training subset rather than extracting generalized patterns, leading to degraded performance on the unseen test set. Therefore, a larger hidden layer does not always improve test accuracy, as a peak capacity balance must be reached.
"""

from IPython.display import display, clear_output
alpha_vals = [0.001, 0.01, 0.05, 0.1]
test_accuracy = []

for a in alpha_vals:
    print(f"\n--- Training with Learning Rate (Alpha) = {a} ---")
    params, train_losses, test_losses, train_accs, test_accs = train_nn(
        X_train_s, y_train, X_test_s, y_test, num_hidden_layer=16, learning_rate=a, epochs=300
    )

    test_accuracy.append(test_accs[-1])

    # Epoch vs Loss plot for specific alpha
    plt.figure(figsize=(6, 4))
    plt.plot(range(1, 301), train_losses, label='Train Loss', color='blue')
    plt.plot(range(1, 301), test_losses, label='Test Loss', color='orange', linestyle='--')
    plt.xlabel("Epochs")
    plt.ylabel("BCE Loss")
    plt.title(f"Epoch vs Loss (Alpha = {a})")
    plt.legend()
    plt.grid(True)
    plt.show()

# Plot for Alpha vs Test Accuracy
plt.figure(figsize=(6, 4))
plt.plot(alpha_vals, test_accuracy, marker='o', color='purple')
plt.xlabel("Alpha values")
plt.ylabel("Final Test Accuracy")
plt.title("Final Test Accuracy vs Alpha Values")
plt.grid(True)
plt.show()

print("\nLearning Rate Results:")
for a, acc in zip(alpha_vals, test_accuracy):
    print(f"Alpha = {a:.3f} -> Final Test Accuracy = {acc:.4f}")

"""## Task 3"""

def train_nn_scheduled(X_train, y_train, X_test, y_test, num_hidden_layer=16, scheduler_type="step", epochs=300):
    num_features = len(X_train[0])
    W1, b1, W2, b2 = init_weights(num_features, num_hidden_layer, random_seed=42)

    train_losses, test_losses = [], []
    train_accs, test_accs = [], []

    # Starting baseline alpha
    current_lr = 0.05 if scheduler_type == "step" else 0.001

    for epoch in range(epochs):
        # 1. Update Learning Rate based on Scheduler Type
        if scheduler_type == "step":
            # Decrease by 1/10th every 100 epochs
            if epoch > 0 and epoch % 100 == 0:
                current_lr = current_lr * 0.1

        elif scheduler_type == "triangular":
            # Gradually scale up to 0.1 over first 150 epochs, then down to 0.001
            midpoint = epochs // 2
            if epoch <= midpoint:
                # Linear ramp up from 0.001 to 0.1
                current_lr = 0.001 + (0.1 - 0.001) * (epoch / midpoint)
            else:
                # Linear ramp down from 0.1 to 0.001
                current_lr = 0.1 - (0.1 - 0.001) * ((epoch - midpoint) / midpoint)

        # 2. Run standard propagation & update step using current_lr
        dW1, db1, dW2, db2 = backprop(X_train, y_train, W1, b1, W2, b2)
        W1, b1, W2, b2 = weight_update(W1, b1, W2, b2, dW1, db1, dW2, db2, current_lr)

        # 3. Metrics tracking
        tr_loss = bce_loss(X_train, y_train, W1, b1, W2, b2)
        te_loss = bce_loss(X_test,  y_test,  W1, b1, W2, b2)
        tr_acc  = calculate_accuracy(X_train, y_train, W1, b1, W2, b2)
        te_acc  = calculate_accuracy(X_test,  y_test,  W1, b1, W2, b2)

        train_losses.append(tr_loss)
        test_losses.append(te_loss)
        train_accs.append(tr_acc)
        test_accs.append(te_acc)

    return test_accs[-1], train_losses, test_losses


# Run and Compare the Schedulers
step_acc, step_tr, step_te = train_nn_scheduled(X_train_s, y_train, X_test_s, y_test, scheduler_type="step")
tri_acc, tri_tr, tri_te = train_nn_scheduled(X_train_s, y_train, X_test_s, y_test, scheduler_type="triangular")

print(f"\n[Scheduler Comparison Summary]")
print(f"Step Decay Scheduler Final Accuracy:       {step_acc:.4f}")
print(f"Triangular (Up/Down) Scheduler Final Accuracy: {tri_acc:.4f}")

"""Scheduler Performance Analysis

Step Decay Scheduler: By dropping the learning rate by a factor of 10 every 100 epochs, this scheduler allows the model to make fast structural leaps early on, then steadily fine-tunes the weight spaces without overshooting minima later.

Triangular Scheduler: The initial ramp-up acts as a "warm-up" phase helping the network break out of poor initial local minima early on, while the smooth cooling down period through the second half ensures smooth optimization convergence.
"""